### ISSUE TITLE
Perfect Pixel 

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#1]
Привести страницу в соответствие с макетом: 

- отрисовать все ряды кнопок, 
- недостающие состояния стрелок, убрать лишние, 
- раскрывающийся список сделать, как в макете, 
- у карты не хватает нижней панели. 

Затем выложить изображение для perfectPixel и настройки.

**Comment by Feinminen** [comment]
Перелопатил почти весь проект, чтобы подогнать к пиксель перфекту и тут сразу несколько вопросиков.
1) Макет же в этом случае нужен только для того чтобы показать какие у элементов размеры и как они меняются при взаимодействии. (т.е. я не понимаю зачем нужны все ряды кнопок, если по факту они будут одинаковыми)
2) Макет ещё более кривой чем первый, центровки, отступы и процентное заполнение некоторых элементов нарисовано явно на глаз. Различия с пиксель перфектом у меня достаточно существенные, но можно же опять пренебречь кривизной, правда ведь ? :D

**Comment by MorganaLF** [comment]
1. Да, в теории так, но тут ведь только по странице UI-Kita можно оценить твои навыки верстать пиксель в пиксель, поскольку остальные страницы придумываются на свое усмотрение. Плюс у тебя, например, в arrow buttons отсутствует состояние задисейбленных кнопок, соответственно, в ui-kite их никак не посмотреть визуально. Ну и если отрисовывать не все элементы, то в перфект пиксель будет сложно проверять, нужно будет под каждый компонент двигать изображение.

2. Да, макет кривой, но там в основном кривость в горизонтальном расположении компонентов относительно друг друга, тут нужно больше внимания уделить, чтобы сами компоненты были пиксель в пиксель. И вертикальные отступы должны совпадать, с этим по идее не должно быть проблем.
Ну и самые наглядные отличия сейчас:  

- отсутствует нижняя панель у карты

![Снимок экрана в 2019-08-22 22-32-16](https://user-images.githubusercontent.com/38564412/63544061-dbe59580-c52c-11e9-8c90-7ba364f3f50d.png)

= выпадающий список в раскрытом состоянии выглядит довольно странно, посмотри в макете, там есть раскрытое состояние.

**Comment by Feinminen** [comment]
Я полностью всё переделал в соответствии с перфект пикселем. Но тут есть одно но, у меня в макете нет раскрытого вида менюхи 
![dropdown](https://user-images.githubusercontent.com/44312820/63601359-73abb800-c5ef-11e9-819d-ddf308550c4f.png)
:C

**Comment by MorganaLF** [comment]
А вот для этого как раз в стандартах написано)

(пункт 7, https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/generalRequirements.md)

> Для всех интерактивных элементов (ссылки, кнопки, дропдауны, инпуты, селекты) дизайнер может прорисовать отдельные состояния и спрятать в ближайшем слое - всегда проверять для каждого элемента, есть ли отрисованное состояние;

![Снимок экрана в 2019-08-23 18-41-35](https://user-images.githubusercontent.com/38564412/63605061-db550980-c5d5-11e9-9613-e45012259894.png)

**Comment by Feinminen** [comment]
Как-то я упустил из виду этот момент 😔. Пофиксил.
P.s. миксин у дропдаун меню криво сделан, завтра переделаю.

**Comment by Feinminen** [comment]
Зарефакторил всё что увидел, можно проверять :)

**Comment by MorganaLF** [comment]
На данный момент сломался ripple-эффект на кнопках, а в messaging отсутствуют иконки

![Снимок экрана в 2019-08-27 00-19-37](https://user-images.githubusercontent.com/38564412/63724454-69442500-c860-11e9-8c14-720a5ea8ba87.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
По responsive: на экранах 1800px и меньше куда-то съезжает messaging. 

![Снимок экрана в 2019-09-01 11-56-20](https://user-images.githubusercontent.com/38564412/64074091-a15bc580-ccaf-11e9-9b3a-67d9c3586db7.png)

Также на маленьких экранах маловато места под perecentages

**Comment by Feinminen** [comment]
Внёс правки.
