### ISSUE TITLE
Инициализация классов

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#10]
Вот это будет неправильно работать в случае, если у тебя будет несколько классов `.calendar` на странице. 

![Снимок экрана в 2019-09-01 11-43-10](https://user-images.githubusercontent.com/38564412/64073973-eda60600-ccad-11e9-9aee-e67eddc2e766.png)

Правильное решение - цикл, но только он должен находиться не в самом классе, а там, где ты делаешь инициализацию, а в каждый экземпляр класса ты уже передаешь только один элемент. 

![Снимок экрана в 2019-09-01 11-45-54](https://user-images.githubusercontent.com/38564412/64074008-35c52880-ccae-11e9-9cb0-df4e56f2634c.png)

И еще заодно тут же напишу: у тебя сейчас вперемешку js и jquery, если ты подключил jquery, то старайся, чтобы было однообразие в проекте. А то немного странно выглядит, что у тебя где-то `querySelectorAll`, где-то $('.calendar'),  `addEventListener`, когда есть `.on`, и т.д.

**Comment by Feinminen** [comment]
Внёс правки. ( циклы пофиксил в js#6, т.к. отдельно было достаточно проблематично закомитить )

**Comment by Feinminen** [comment]
Насчёт jQuery -  я его подключал только для того чтобы сделать календарь и его синтаксис присутствует только там(функции календаря самому пилить ну очень долго). Думаю это вполне допустимое использование библиотеки)

**Comment by MorganaLF** [comment]
Посмотри еще внимательно, где-то ты вообще не передаешь элемент в параметры класса при инициализации, где-то берешь только первый элемент (а что если на странице их будет больше?), где-то делаешь поиск по всем элементам и передаешь массив, и т.д.:

![Снимок экрана в 2019-09-07 22-20-20](https://user-images.githubusercontent.com/38564412/64479308-b22f9e00-d1bd-11e9-9f92-80deb397ac2d.png)

**Comment by Feinminen** [comment]
Внёс правки.
