### ISSUE TITLE
Инлайновые стили

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#11]
Здесь нет необходимости все правила задавать инлайн, ты можешь задать `background-image` в pug, а все остальное в sass.

![Снимок экрана в 2019-09-01 12-02-39](https://user-images.githubusercontent.com/38564412/64074166-a1a89080-ccb0-11e9-9902-4cd74e5c3301.png)

**Comment by Feinminen** [comment]
Внёс правки.
