### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#14]
Компонент Search

Это уже захардкоженность, лучше передавать текст через параметры в pug, а оттуда в data-атрибуты

![Снимок экрана в 2019-09-10 16-33-30](https://user-images.githubusercontent.com/38564412/64618407-e2a75000-d3e8-11e9-96cb-e040b472f2e8.png)

**Comment by MorganaLF** [comment]
Компонент Stages:

Здесь у тебя прямо в js зашито, какой шаг выставлен активным при инициализации? Это должно настраиваться в pug. 

![Снимок экрана в 2019-09-10 16-40-22](https://user-images.githubusercontent.com/38564412/64618906-d4a5ff00-d3e9-11e9-95c1-95b6fa4a5075.png)

И заодно сразу, чтобы не открывать новое ишью, напишу другие замечания: если ты проходишь по элементам массива, используй forEach, не надо добавлять классы каждому элементу отдельно.

Дальше обрати внимание, что у тебя вот тут не сравнение, а присваивание:

![Снимок экрана в 2019-09-10 16-43-14](https://user-images.githubusercontent.com/38564412/64619074-2484c600-d3ea-11e9-96f3-a3ed502a3f89.png)

**Comment by MorganaLF** [comment]
Компонент Slider

Насколько я поняла, тут у тебя тоже настройки в js зашиты? Здесь в pug должна быть возможность устанавливать минимум, максимум, размер шага, текущее значение.

**Comment by MorganaLF** [comment]
Компонент Stages
Тут у тебя селектор, который противоречит противоречит БЭМ. И в английском точно есть слово unachive?)

![Снимок экрана в 2019-09-10 19-33-03](https://user-images.githubusercontent.com/38564412/64632547-ef846d80-d401-11e9-9182-25c98b885d34.png)

**Comment by Feinminen** [comment]
Насчет того что было присваивание - это были так реализованы функции(слегка странновато, но это самая короткая реализация :D). Переделал, чтобы было понятнее что происходит.

**Comment by Feinminen** [comment]
> Компонент Slider
> 
> Насколько я поняла, тут у тебя тоже настройки в js зашиты? Здесь в pug должна быть возможность устанавливать минимум, максимум, размер шага, текущее значение.

Там настройки даже не в js зашиты, их просто нет, ибо скрипт не предполагает того что можно будет поменять шаг/размер/минимум/максимум. Он может менять только то что меняется в макете: стартовую позицию/наличие тултипа/наличие прогресс бара и шкалы.

Если тут реализовывать возможность выбора шага и размеров, то можно просто будет закинуть в этот проект - следующий проект(слайдер), что слегка странновато. Я же не подключал для слайдера jq плагин, поэтому реализовал только базовый функционал, для элементов, которые менялись в макете.
