### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#15]
**Pug:**

Здесь не список одной кнопки, а список кнопок, buttonsList

![Снимок экрана в 2019-09-12 21-49-38](https://user-images.githubusercontent.com/38564412/64812124-47100e00-d5a7-11e9-8141-e093ef0c85c2.png)

`options-list`

![Снимок экрана в 2019-09-12 21-51-36](https://user-images.githubusercontent.com/38564412/64812258-86d6f580-d5a7-11e9-942b-ce36592df746.png)

Здесь просто month, зачем перед ним стоит `date-`?

![Снимок экрана в 2019-09-12 21-53-57](https://user-images.githubusercontent.com/38564412/64812446-ea612300-d5a7-11e9-949c-e06bc6bb8aca.png)

`timer-donut` и `fill-donut` неподходящие названия для блоков, они просто описывают их внешний вид, из названия непонятно, что это диаграммы. Ну и заодно тут в переменных списков тоже поправишь на множественное число.

![Снимок экрана в 2019-09-12 22-10-27](https://user-images.githubusercontent.com/38564412/64813605-69eff180-d5aa-11e9-9386-8b0d520631ba.png)

`dataNotFound` тоже непонятное название, errorText, может быть

![Снимок экрана в 2019-09-12 22-14-11](https://user-images.githubusercontent.com/38564412/64813773-d3700000-d5aa-11e9-9c36-e458844b2da6.png)

Что означает `.search__input-glass`, почему так называется элемент?

![Снимок экрана в 2019-09-12 22-16-50](https://user-images.githubusercontent.com/38564412/64813906-1cc04f80-d5ab-11e9-8d42-1006e47987b1.png)

buttonsList

![Снимок экрана в 2019-09-12 22-20-15](https://user-images.githubusercontent.com/38564412/64814122-8b051200-d5ab-11e9-8d90-799448698ebf.png)

В англ. языке должно быть наоборот, facebook link, и т.д...

![Снимок экрана в 2019-09-12 22-24-04](https://user-images.githubusercontent.com/38564412/64814426-1da5b100-d5ac-11e9-98da-e312d1def7ec.png)

**Comment by MorganaLF** [comment]
calendar.sass

Здесь у тебя есть "текущий день", "текущий месяц" и просто `current` - "текущий".  По названию последнего непонятно, что это за элемент. `current-content` тоже непонятное название - текущий контент?

![Снимок экрана в 2019-09-16 19-45-37](https://user-images.githubusercontent.com/38564412/64976779-d163b500-d8ba-11e9-8169-9e2bb633e548.png)

**Comment by MorganaLF** [comment]
**Js**

Компонент PercentagePieChart
Что означают названия этих свойств?

![Снимок экрана в 2019-09-16 20-04-04](https://user-images.githubusercontent.com/38564412/64978031-3ddfb380-d8bd-11e9-8066-0c9582b97708.png)

Search
Здесь ты поменял название элемента, а в переменной остался glass

![Снимок экрана в 2019-09-16 20-06-01](https://user-images.githubusercontent.com/38564412/64978144-85663f80-d8bd-11e9-854b-d37c7d2a4132.png)

Slider
Здесь у тебя метод называется setPrecentage, хотя делает он явно что-то другое, по всей видимости обновляет положение элементов слайдера.

![Снимок экрана в 2019-09-16 20-07-54](https://user-images.githubusercontent.com/38564412/64978484-45ec2300-d8be-11e9-818c-92f61495cf8c.png)

Блок Stage прямо весь надо проверить, почти все переменные называются слишком абстрактно, либо непонятно. Ширина - ширина чего? Результат - что за результат? И так далее.

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
По PercentagePieChart пропустил) По-моему тут с английского если переводить наименования, получится просто набор слов. 

В Stages остались еще не очень удачные переменные. `targetInnerHtml `- это просто повторение того же самого, что написано в js. Что у тебя там лежит в переменной? Там ведь не просто inner html, а какое-то конкретное значение.

Названия методов `prevAll` и `nextAll` - по ним тоже совершенно непонятно, что делают эти методы. 

Дальше, все переменные, где фигурирует prev и next - наверное, это ведь не просто предыдущие и следующие элементы, скорее, пройденные и не пройденные шаги? Или может какое-то более подходящее название?

**Comment by Feinminen** [comment]
Внёс правки, надеюсь всё ок по наименованиям) Т.к. , насколько я понял, методы лучше называть действиями, назвал метод возвращающий элементы через "return", надеюсь это допустимо.

**Comment by MorganaLF** [comment]
По `PercentagePieChart` были нужны другие правки, не название блока)) Выше я скидывала скрин с названиями свойств, которые лежат в `PercentagePieChart`: свойства конструктора `currentValueFill `и `currentValueEmpty`.

Сейчас появился доп. вопрос - к новому названию самого блока: что значит progressive chart, как это переводится?) Те же самые вопросы к названиям свойств `currentValueFill `и `currentValueEmpty`.

![Снимок экрана в 2019-09-23 15-00-40](https://user-images.githubusercontent.com/38564412/65423956-05872a80-de13-11e9-8c25-21128c2e4e33.png)

**Comment by Feinminen** [comment]
> По `PercentagePieChart` были нужны другие правки, не название блока))

Хех, как-то я действительно пропустил. Хотел ещё обосновать название старого блока, но решил что быстрее будет поменять на другой C: На данный момент у меня была такая логика: данная диаграмма отображает процент заполнения шкалы => скорее всего, это будет какой-то прогресс => это круговая диаграмма указывающая прогресс, в итоге получилась "прогрессивная диаграмма". P.s. не могу сказать что данное название блока претендует на абсолютную "понятность", но и предыдущее название было тоже понятно лишь в какой-то степени - "процентная круговая диаграмма".

**Comment by MorganaLF** [comment]
Тогда лучше progress chart - диаграмма прогресса, так больше смысла, чем прогрессивная диаграмма)

**Comment by Feinminen** [comment]
> Те же самые вопросы к названиям свойств `currentValueFill `и `currentValueEmpty`.
Поменял названия, переменные показывают процент заполненной и пустой шкалы соответственно. Надеюсь так будет корректно. Также уже обновил версию ui-kit-page
