### ISSUE TITLE
Абсолютное позиционирование и вертикальное выравнивание

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#16]
Сейчас у тебя иконки вертикально выравниваются с указанием конкретных значений. Это противоречит стандартам, и при уменьшении ширины экрана иконки оказываются не по центру. Насколько я помню, там вообще в макете есть эти иконки в виде svg, так что нет необходимости что-то абсолютно позиционировать и вот так выравнивать. 

![Снимок экрана в 2019-09-16 20-31-23](https://user-images.githubusercontent.com/38564412/64979873-4df99200-d8c1-11e9-9019-79849d9c2135.png)

**Comment by MorganaLF** [comment]
С dropdown вообще что-то непонятное, кнопка отдельно, иконка отдельно, все с абсолютным позиционированием и странным центрированием. Иконку надо поместить в кнопку и отцентрировать

![Снимок экрана в 2019-09-16 20-37-11](https://user-images.githubusercontent.com/38564412/64980078-ca8c7080-d8c1-11e9-8fdf-21977ed1e2b9.png)

**Comment by MorganaLF** [comment]
Блок video
Тут нет никакой необходимости внутри панели абсолютно позиционировать дорожку и кнопки, с этим отлично справится флексбокс 

![Снимок экрана в 2019-09-16 20-43-55](https://user-images.githubusercontent.com/38564412/64980545-b85f0200-d8c2-11e9-819c-8e2fe0233367.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Хорошо, только в блоке видео ты сделал модификаторы для кнопок и их названия снова противоречат стандартам - названы существительными)

**Comment by Feinminen** [comment]
Пофиксил, я понимаю что это часть стандарта, но я не особо вижу логику в том что мы добавляем "with" к существительному и, вроде как, у нас получается что-то похожее на прилагательное(хотя на вопросы прилагательного сие сущность не отвечает). Поэтому и забываю постоянно :C

**Comment by MorganaLF** [comment]
> Пофиксил, я понимаю что это часть стандарта, но я не особо вижу логику в том что мы добавляем "with" к существительному

Оно теперь отвечает на вопрос "какой?", а не "что?". Смысл модификатора в том, что он описывает свойства твоего блока / элемента, то есть каким он является. Если ты пишешь video_pause, то это по смыслу больше напоминает элемент, то есть чем он является, а не каким.
