### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#2]
Вот этот слайдер должен передвигаться по значениям шкалы, то есть, он может иметь значения только 0, 25, 50 и т.д.

![Снимок экрана в 2019-08-27 00-21-27](https://user-images.githubusercontent.com/38564412/63724600-d061d980-c860-11e9-9a32-c6eab0562616.png)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Из-за неправильных названий файлов в путях проект не собирается, проверь регистр

![Снимок экрана в 2019-09-01 10-54-09](https://user-images.githubusercontent.com/38564412/64073460-e5969800-cca6-11e9-8a5c-ccdb646c542c.png)

**Comment by MorganaLF** [comment]
И еще не забывай обновлять gh-pages

**Comment by Feinminen** [comment]
Очень странно что проект не собирается, у меня всё ок(и с регистрами и с путями в целом). Gh-pages обновил.

**Comment by Feinminen** [comment]
А, нашёл в чем проблема, на гитхабе названия файлов не обновились, щас попытаюсь исправить

**Comment by Feinminen** [comment]
Внёс правки. Я слегка извратился, чтобы называния поменять, но по другому не получалось)
