### ISSUE TITLE
Пересоздание слайдера при ресайзе

### ISSUE THREAD

**Issue by Znack** [Feinminen/FSD-Ui-kit#23]
Почему каждый раз при ресайзе [слайдер создается заново](https://github.com/Feinminen/FSD-Ui-kit/blob/master/src/blocks/slider/index.js#L7-L9)? А не обрабатывает это событие внутри? И если происходит создание нового, то почему нет уничтожения старого?

**Comment by Feinminen** [comment]
Внёс правки. Коммит с изменениями слайдера в соседнем ишью.
