### ISSUE TITLE
slider-section / slider

### ISSUE THREAD

**Issue by Frolikow** [Feinminen/FSD-Ui-kit#30]
1) `slider-section`. Не совсем ясна вложенность слайдеров. Один слайдер в элементе `item`, а второй в родительском `content`. Наверно для второго слайдера забыл сделать обертку в виде еще одного `item`'a?
![image](https://user-images.githubusercontent.com/25764783/70442385-d191dc00-1ac8-11ea-8fbc-7b82cabcbff8.png)
___
2) slider
2.1)
в самом слайдере не понял что ты хотел сделать модификаторами. Одинаковые модификаторы для разных элементов. По сути этот повторяющийся модификатор подойдет только для элемента `slider__tooltip`. На остальных получается что попало. Элемент один, а модификатор на нем от другого элемента(`.slider__progress.slider__tooltip_orange`).
```pug
mixin slider({ hasProgress, hasTooltip, hasRangeLabels, tooltipModifier, progressModifier, thumbModifier, startPosition= "40", stepSize="1", minValue="0", maxValue="100" })
  -
    const tooltipModifiers = {
      orange: "slider__tooltip_orange"
    };

    const progressModifiers = {
      orange: "slider__tooltip_orange"
    };
    
    const thumbModifiers = {
      orange: "slider__tooltip_orange"
    };

  .slider.js-slider(data-startposition=startPosition, data-stepsize=stepSize, data-minvalue=minValue, data-maxvalue=maxValue)
    .slider__track
      if hasProgress
        .slider__progress(class=progressModifiers[progressModifier])
    .slider__thumb(class=thumbModifiers[thumbModifier])
    if hasTooltip
      .slider__tooltip(class=tooltipModifiers[tooltipModifier])
    if hasRangeLabels
      ul.slider__range-labels.js-slider__range-labels
```

2.2) Здесь кажется забыл про префикс `js-`
![image](https://user-images.githubusercontent.com/25764783/70443368-985a6b80-1aca-11ea-8e25-d9769d9ea069.png)
![image](https://user-images.githubusercontent.com/25764783/70444335-4b779480-1acc-11ea-944b-9f7b8dc41fb3.png)
 _Это не единственное место в проекте с такой же ошибкой._ 

2.3) Когда пишешь дата-атрибуты, не надо писать несколько слов в одно, подобные вещи пишутся обычно в нотации kebab-case(через `-`). А в js ты к этим атрибутам можешь обратиться через camelCase. Например: `data-step-size=stepSize` в js будет доступен как `this.sliderContainer.dataset.stepSize`
![image](https://user-images.githubusercontent.com/25764783/70444205-1cf9b980-1acc-11ea-8d05-b80f449c2319.png)
 _Это не единственное место в проекте с такой же ошибкой._

**Comment by Feinminen** [comment]
С модификаторами из-за копипаста так получилось, я классы модификаторов для всех элементов создал, а в PUG один и тот же класс указал.
Тут ещё один коммит в ветке должен быть с исправлением data атрибутов и префиксов, но я с '#' промахнулся, надеюсь не критично :(
