### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#4]
Из стандартов:

> Всегда использовать как минимум один запасной шрифт и одно запасное семейство;

![Снимок экрана в 2019-08-27 00-28-16](https://user-images.githubusercontent.com/38564412/63724896-9513da80-c861-11e9-8c56-c48304de5bd0.png)

И лучше бы у html задать размер шрифта не только в медиазапросах, но и по умолчанию.

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Проверь по всему проекту, где еще надо исправить:

![Снимок экрана в 2019-09-01 11-40-44](https://user-images.githubusercontent.com/38564412/64073932-6d7fa080-ccad-11e9-8e33-9ab89562a165.png)

**Comment by Feinminen** [comment]
Внёс правки.
