### ISSUE TITLE
Arrow buttons

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#5]
Эти комментарии никакой особой необходимости не имеют, у тебя ведь по объекту модификаторов и так видно, какие значения они могут принимать

![Снимок экрана в 2019-08-27 00-33-37](https://user-images.githubusercontent.com/38564412/63725261-87ab2000-c862-11e9-9598-9f84181b6675.png)

Дальше у тебя опять та же ошибка, что и в прошлом проекте: ты в компоненте кнопки выводишь цикл, цикл должен выводиться в родительском компоненте, который использует кнопку. `arrow-buttons-section` например. А здесь сделать просто компонент для одной кнопки.

Посмотри по всему проекту, встречается ли где-то еще такое.

**Comment by Feinminen** [comment]
Внёс правки.
