### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#6]
JS каждого блока должен быть классом.

**Comment by Feinminen** [comment]
Внёс правки, вроде бы ничего не сломал)

**Comment by Feinminen** [comment]
Псст?

**Comment by MorganaLF** [comment]
Один метод должен выполнять только одну задачу, сейчас у тебя переписывание на классы почти везде свелось к тому, что ты просто весь js поместил в метод init, хотя у тебя там происходит не только инициализация. 

Например, в классе `Location` создание placemark можно вынести в отдельный метод, и заодно поправить название переменной myPlacemark, my там явно неуместно)

То же самое с `ReviewForm`, например, или `Calendar`, где у тебя в `init` оказалась функция `setDate`, и т.д.

**Comment by MorganaLF** [comment]
Вообще все классы надо внимательно посмотреть, и поубирать из init все, что выполняет другую задачу. Обработчики событий также вынести отельно.

**Comment by MorganaLF** [comment]
Что делает метод push? По его названию совсем непонятно.

![Снимок экрана в 2019-09-01 11-30-03](https://user-images.githubusercontent.com/38564412/64073829-0d3c2f00-ccac-11e9-9bc2-12a11cf445fa.png)

**Comment by MorganaLF** [comment]
Еще у тебя не соблюдены требования стандартов о том, что все классы, которые используются для поиска по DOM, должны иметь префикс `js-`

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Посмотри в стандартах, как именовать обработчики событий и вообще о том, что они должны быть вынесены в отдельные функции: 

https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md пункт 11

**Comment by Feinminen** [comment]
Внёс правки.
