### ISSUE TITLE
standard-button

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#7]
У тебя сейчас есть блок `standard-button`, который используется только в первой секции, хотя аналогичные кнопки есть в контактной форме, событиях и сообщениях. Они лишь немного отличаются и для этого как раз пригодятся модификаторы.

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
Здесь у тебя снова в scss дублирование свойств. У тебя ide не подсвечивает такое?

![Снимок экрана в 2019-09-07 21-54-23](https://user-images.githubusercontent.com/38564412/64479060-22d4bb80-d1ba-11e9-9a5d-dc0de51ba381.png)

**Comment by Feinminen** [comment]
Убрал дублирование, моя IDE не подсвечивает такое, что слегка странновато. Я сам весь проект пробегал глазами, а он не такой уж и маленький, хех
