### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#8]
Почитай в стандартах в соглашении об именованиях, как правильно именовать модификаторы (https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md). "вверх", "вниз", "блок" - это все некорректные названия, модификатор должен отвечать на вопрос "какой"?

![Снимок экрана в 2019-09-01 11-28-14](https://user-images.githubusercontent.com/38564412/64073812-9acb4f00-ccab-11e9-953b-b8f30900cf27.png)

**Comment by MorganaLF** [comment]
Почему бы не сделать это модификаторами? И как раз заюзать переменные цвета в sass

![Снимок экрана в 2019-09-01 12-09-44](https://user-images.githubusercontent.com/38564412/64074250-8e49f500-ccb1-11e9-93f7-799ed1db98f9.png)

**Comment by MorganaLF** [comment]
![Снимок экрана в 2019-09-01 12-15-32](https://user-images.githubusercontent.com/38564412/64074341-79ba2c80-ccb2-11e9-86c4-5a2bfbf1eb9c.png)

Еще пример. Надо проверить везде.

**Comment by MorganaLF** [comment]
Вот здесь name и email имеют одинаковые стили, для них нет необходимости создавать разные элементы блока

![Снимок экрана в 2019-09-01 12-21-48](https://user-images.githubusercontent.com/38564412/64074407-7a9f8e00-ccb3-11e9-89ea-1c1bb0e9a525.png)

**Comment by Feinminen** [comment]
> Почему бы не сделать это модификаторами? И как раз заюзать переменные цвета в sass
> 
> ![Снимок экрана в 2019-09-01 12-09-44](https://user-images.githubusercontent.com/38564412/64074250-8e49f500-ccb1-11e9-93f7-799ed1db98f9.png)

На мой взгляд, с модификаторами получится крайне не вариативно, т.к. размеры дуги у сегментов будут одинаковые и поменять их никак не получится. (модификаторы для цвета я добавил)

**Comment by Feinminen** [comment]
Внёс правки.

**Comment by MorganaLF** [comment]
"Левая" и "правая" иконки - это совсем не удобные названия: а что, если они поменяются местами? Еще раз кидаю ссылку, где описывается, как именовать модификаторы. https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md Там как раз есть пример про error, по аналогии с которым можно сделать.

**Comment by MorganaLF** [comment]
> > Почему бы не сделать это модификаторами? И как раз заюзать переменные цвета в sass
> > ![Снимок экрана в 2019-09-01 12-09-44](https://user-images.githubusercontent.com/38564412/64074250-8e49f500-ccb1-11e9-93f7-799ed1db98f9.png)
> 
> На мой взгляд, с модификаторами получится крайне не вариативно, т.к. размеры дуги у сегментов будут одинаковые и поменять их никак не получится. (модификаторы для цвета я добавил)

Здесь я как раз модификаторы цвета имела ввиду. 
А вот stroke-dasharray, stroke-dashoffset по идее по формуле должны считаться, а так у тебя получается, чтобы заюзать диаграмму, надо вручную посчитать все данные. Извне тут нужно знать только проценты сегментов, все остальное должно считаться внутри. Ширину обводки можно перенести в .fill-donut__segment.

**Comment by Feinminen** [comment]
>А вот stroke-dasharray, stroke-dashoffset по идее по формуле должны считаться, а так у тебя получается, чтобы заюзать диаграмму, надо вручную посчитать все данные. Извне тут нужно знать только проценты сегментов, все остальное должно считаться внутри.

Да, определённо выбор позиционирования сегментов должен задаваться по формулам, но делать это в PUG слегка самоубийство. Т.к. у каждого из элементов помимо позиционирования ещё и отступы должны правильно рассчитываться относительно начала координат пайчарта, там взаимодействий между переменными будет очень много и ограничений по их назначению тоже. Для того чтобы удобно было создавать подобного рода чарты - нужен целый пользовательский интерфейс, по-хорошему) Ширину обводки я вынес, модификаторы для цвета добавил, можно дальше оставить блок в таком виде? 🌵

**Comment by MorganaLF** [comment]
Ну для реального проекта такое точно бы не подошло, представь, что в проекте есть такой компонент и каждому участнику команды, чтобы его использовать, надо вручную считать dasharray и dashoffset) Спасибо точно никто не скажет) Я это делала через js, но думаю, это вполне можно и в pug перенести, можешь у меня посмотреть, как это все считается. https://github.com/MorganaLF/FlatUI/blob/master/src/components/ui-kit-components/chart/Chart.js

**Comment by MorganaLF** [comment]
Компонент Slider:
Вот это тоже надо сделать модификаторами

![Снимок экрана в 2019-09-10 19-29-36](https://user-images.githubusercontent.com/38564412/64632243-65d4a000-d401-11e9-834d-89fbd75f646f.png)

**Comment by MorganaLF** [comment]
Компонент Stages
Тут у тебя селектор, который противоречит противоречит БЭМ. И в английском точно есть слово unachive?)

![Снимок экрана в 2019-09-10 19-33-03](https://user-images.githubusercontent.com/38564412/64633452-e4cad800-d403-11e9-9bd9-26dd2a7e96b9.png)

**Comment by MorganaLF** [comment]
Компонент Video
Почему кнопка с id вместо класса?

![Снимок экрана в 2019-09-10 19-47-17](https://user-images.githubusercontent.com/38564412/64633525-03c96a00-d404-11e9-8b5c-8082277f4900.png)

**Comment by MorganaLF** [comment]
Не сразу обратила внимание - иконки соц. сетей также стоит сделать с модификаторами - у них отличается только background-image, его вынести в модификатор, а остальное оставить элементу.

**Comment by Feinminen** [comment]
Внёс правки.
