### ISSUE TITLE
Дублирование в css

### ISSUE THREAD

**Issue by MorganaLF** [Feinminen/FSD-Ui-kit#9]
Старайся, чтобы у тебя в css не было дублирования css-правил, например здесь ты дважды указал cursor: pointer

![Снимок экрана в 2019-09-01 11-37-47](https://user-images.githubusercontent.com/38564412/64073901-f2b68580-ccac-11e9-89c8-61f291189283.png)

**Comment by MorganaLF** [comment]
Здесь можно в margin задать отступ сверху, не нужно писать margin-top отдельно

![Снимок экрана в 2019-09-01 12-11-59](https://user-images.githubusercontent.com/38564412/64074271-ccdfaf80-ccb1-11e9-88ea-0273601f4b6f.png)

**Comment by MorganaLF** [comment]
Это всё просто отдельные примеры, надо посмотреть везде

**Comment by MorganaLF** [comment]
Вот здесь name и email имеют одинаковые стили, для них нет необходимости создавать разные элементы блока

![Снимок экрана в 2019-09-01 12-21-48](https://user-images.githubusercontent.com/38564412/64074399-5a6fcf00-ccb3-11e9-8e00-458bbda62cf0.png)

**Comment by Feinminen** [comment]
Внёс правки.
